### PR TITLE
Created plugin, updated demo, fixed time display

### LINKED ISSUE #17: Create a Messages plugin
# Kuchulem_Messages

Will provide a way to override the messages parsing system to use an extensible service instead. This service would allow scripters to add message parsers in other plugins.

## Usage

The custom parser should be an instance of a `Kuchulem_Messages_Parser` prototype with the following signature:

```js
/**
 * @param {string} controlCaracter The group of letters to match to activate the callback
 * @param {boolean} hasParameter Wether a parameter between brackets is expected
 * @param {Function} callback A function to call that receives the parameter if any  and
 * the message parser instanc eand returns a string
 */
function Kuchulem_Messages_Parser(controlCaracter, hasParameter, callback) {}
```

usage example in NPC plugin:

```js
// This parser expects a "Npc.firstName" controlCharater with parameter (second argument to true)
// In the message it will look like \Npc.firstName[3]
const parser = new Kuchulem_Messages_Parser("Npc.firstName", true, (messageParser, id) => {
    const npcId = Number(id); // the parameter will probably be a string
    return $gameNpcs.npc(npcId).firstName();
});
```

The message parser argument for the callback could be use to execute parsers on the string before returning it.

usage example in i18n plugin:

```js
// This parser expects a "_" controlCharater with parameter (second argument to true)
// In the message it will look like \_[greetings_from_npc_1]
const parser = new Kuchulem_Messages_Parser("_", true, (messageParser, i18nToken) => {
    const text = $i18n.localize(i18nToken) // "Hello, I'm \Npc.firstName[1]"
    return messageParser.parse(text);
});
```

## Expected
- The parser MUST be extensible through a `registerParser` method
- The custom parsers MUST be able to run the parsing service on the string they return

### LINKED ISSUE #25: Lag on the time display
When displaying time, the longer it is displayed the more the game lag when the bitmap is updated.

How to reproduce : 
- Run the demo
- Wait for the clock to update
- move the character while time passes
The more time passes the more the game lags

When deactivating the Game_Time plugin (and dependant plugins) the lag disapears

### PR DESCRIPTION
**Pull request by anthony-maudry**
Closes #17
- created the `Kuchulem_Messages` plugin

Fixes #25
- fxed an error in code that made the game running slower over time when clock is displayed

### CODE REVIEW

File: demo/Kuchulem_Demo/js/plugins/Kuchulem_Npcs.js [hunk 1]
```diff
@@ -424,15 +428,57 @@ Kuchulem_Npcs_GameNpcs.prototype.unsetNpcEvent = function(mapId, eventId) {
...
+                case "FULLNAME":
+                    return `\\Npc{FIRSTNAME}[${npc.id}] \\Npc{LASTNAME}[${npc.id}]`
+            }
+        };
+    }
+
+    $messageParsers.registerParser(new Kuchulem_Npc_MessageParser());
+    //#endregion
+
+
```
Comment (anthony-maudry) [inline demo/Kuchulem_Demo/js/plugins/Kuchulem_Npcs.js]: unecessary NL

File: demo/Kuchulem_Demo/js/plugins/Kuchulem_Events.js [hunk 2]
```diff
@@ -231,6 +234,8 @@ Kuchulem_Events_Publisher.offSwitchEvent = function(eventName, switchId, callbac
  * @param {Object} publisherClass 
  */
 Kuchulem_Events_Publisher.prototype.publish = function(eventName, publisher) {
+    if (eventName === Game_Map_events.beforeRefresh) {
+    }
```
Comment (anthony-maudry) [inline demo/Kuchulem_Demo/js/plugins/Kuchulem_Events.js]: ???

File: demo/Kuchulem_Demo/js/plugins/Kuchulem_GameTime.js [hunk 3]
```diff
@@ -265,11 +279,10 @@ Sprite_Clock.prototype.updateBitmap = function() {
  * Redraws the bitmap content
  */
 Sprite_Clock.prototype.redraw = function() {
+    console.log("redraw");
```
Comment (anthony-maudry) [inline demo/Kuchulem_Demo/js/plugins/Kuchulem_GameTime.js]: !!!

File: demo/Kuchulem_Demo/js/plugins/Kuchulem_Base.js [hunk 4]
```diff
@@ -79,8 +79,43 @@ function Kuchulem() {
...
+            Kuchulem._gameObjectCreatedListeners = [];
+        }
+        if (!!window[gameObjectName]) {
+            callback.call(thisArg ?? window, window[gameObjectName]);
+        } else {
+            Kuchulem._gameObjectCreatedListeners.push([gameObjectName, callback, thisArg]);
+        }
+    }
+
+    Kuchulem.gameObjectCreatedListeners = function(gameObjectName) {
```
Comment (anthony-maudry) [inline demo/Kuchulem_Demo/js/plugins/Kuchulem_Base.js]: Still used ?
